const languages_data = {
  en: {
    greeting: "Welcome to the Chat App Thing!",
    choose_nickname: "Choose your nickname",
    username_input_empty_error: "Please enter a username.",
    join: "Join",
    users: "user(s)",
    rooms: "Rooms",
    create_room: "Create Room",
    send_pm: "Send PM",
    create_new_room: "Create a new room",
    room_name: "Room name",
    create: "Create",
    create_pm_room: "Create a Private Message Room",
    user_name: "User name",
    change_theme: "Change Theme",
    change_language: "Change Language",
  },
  tr: {
    greeting: "Chat Uygulaması Gibi Şeye Hoşgeldiniz!",
    choose_nickname: "Kullanıcı adı seçin",
    username_input_empty_error: "Lütfen bir kullanıcı adı giriniz",
    join: "Katıl",
    users: "kullanıcı(lar)",
    rooms: "Odalar",
    create_room: "Oda Oluştur",
    send_pm: "PM Yolla",
    create_new_room: "Yeni bir oda oluştur.",
    room_name: "Oda ismi",
    create: "Oluştur",
    create_pm_room: "Özel mesaj odası oluştur",
    user_name: "Kullanıcı adı",
    change_theme: "Tema Degistir",
    change_language: "Dil Değiştir",
  },
};

export default languages_data;
